<?php


 function autoload_e0abf0ee92872913d76e44772719e2ec($class)
{
    $classes = array(
        'App\DHL\GVAPI_2_0_de' => __DIR__ .'/GVAPI_2_0_de.php',
        'App\DHL\Version' => __DIR__ .'/Version.php',
        'App\DHL\AuthentificationType' => __DIR__ .'/AuthentificationType.php',
        'App\DHL\NativeAddressType' => __DIR__ .'/NativeAddressType.php',
        'App\DHL\ReceiverNativeAddressType' => __DIR__ .'/ReceiverNativeAddressType.php',
        'App\DHL\PickupAddressType' => __DIR__ .'/PickupAddressType.php',
        'App\DHL\DeliveryAddressType' => __DIR__ .'/DeliveryAddressType.php',
        'App\DHL\BankType' => __DIR__ .'/BankType.php',
        'App\DHL\NameType' => __DIR__ .'/NameType.php',
        'App\DHL\ReceiverNameType' => __DIR__ .'/ReceiverNameType.php',
        'App\DHL\CommunicationType' => __DIR__ .'/CommunicationType.php',
        'App\DHL\ContactType' => __DIR__ .'/ContactType.php',
        'App\DHL\PackStationType' => __DIR__ .'/PackStationType.php',
        'App\DHL\PostfilialeType' => __DIR__ .'/PostfilialeType.php',
        'App\DHL\ParcelShopType' => __DIR__ .'/ParcelShopType.php',
        'App\DHL\CustomerType' => __DIR__ .'/CustomerType.php',
        'App\DHL\ErrorType' => __DIR__ .'/ErrorType.php',
        'App\DHL\CountryType' => __DIR__ .'/CountryType.php',
        'App\DHL\ShipmentNumberType' => __DIR__ .'/ShipmentNumberType.php',
        'App\DHL\Status' => __DIR__ .'/Status.php',
        'App\DHL\Dimension' => __DIR__ .'/Dimension.php',
        'App\DHL\TimeFrame' => __DIR__ .'/TimeFrame.php',
        'App\DHL\GetVersionResponse' => __DIR__ .'/GetVersionResponse.php',
        'App\DHL\CreateShipmentOrderRequest' => __DIR__ .'/CreateShipmentOrderRequest.php',
        'App\DHL\ValidateShipmentOrderRequest' => __DIR__ .'/ValidateShipmentOrderRequest.php',
        'App\DHL\CreateShipmentOrderResponse' => __DIR__ .'/CreateShipmentOrderResponse.php',
        'App\DHL\ValidateShipmentResponse' => __DIR__ .'/ValidateShipmentResponse.php',
        'App\DHL\GetLabelRequest' => __DIR__ .'/GetLabelRequest.php',
        'App\DHL\GetLabelResponse' => __DIR__ .'/GetLabelResponse.php',
        'App\DHL\DoManifestRequest' => __DIR__ .'/DoManifestRequest.php',
        'App\DHL\DoManifestResponse' => __DIR__ .'/DoManifestResponse.php',
        'App\DHL\DeleteShipmentOrderRequest' => __DIR__ .'/DeleteShipmentOrderRequest.php',
        'App\DHL\DeleteShipmentOrderResponse' => __DIR__ .'/DeleteShipmentOrderResponse.php',
        'App\DHL\GetExportDocRequest' => __DIR__ .'/GetExportDocRequest.php',
        'App\DHL\GetExportDocResponse' => __DIR__ .'/GetExportDocResponse.php',
        'App\DHL\GetManifestRequest' => __DIR__ .'/GetManifestRequest.php',
        'App\DHL\GetManifestResponse' => __DIR__ .'/GetManifestResponse.php',
        'App\DHL\UpdateShipmentOrderRequest' => __DIR__ .'/UpdateShipmentOrderRequest.php',
        'App\DHL\UpdateShipmentOrderResponse' => __DIR__ .'/UpdateShipmentOrderResponse.php',
        'App\DHL\CreationState' => __DIR__ .'/CreationState.php',
        'App\DHL\ValidationState' => __DIR__ .'/ValidationState.php',
        'App\DHL\Statusinformation' => __DIR__ .'/Statusinformation.php',
        'App\DHL\PieceInformation' => __DIR__ .'/PieceInformation.php',
        'App\DHL\ShipmentOrderType' => __DIR__ .'/ShipmentOrderType.php',
        'App\DHL\Shipment' => __DIR__ .'/Shipment.php',
        'App\DHL\ValidateShipmentOrderType' => __DIR__ .'/ValidateShipmentOrderType.php',
        'App\DHL\ShipperTypeType' => __DIR__ .'/ShipperTypeType.php',
        'App\DHL\ShipperType' => __DIR__ .'/ShipperType.php',
        'App\DHL\ReceiverTypeType' => __DIR__ .'/ReceiverTypeType.php',
        'App\DHL\ReceiverType' => __DIR__ .'/ReceiverType.php',
        'App\DHL\Ident' => __DIR__ .'/Ident.php',
        'App\DHL\ShipmentDetailsType' => __DIR__ .'/ShipmentDetailsType.php',
        'App\DHL\ShipmentDetailsTypeType' => __DIR__ .'/ShipmentDetailsTypeType.php',
        'App\DHL\ShipmentItemType' => __DIR__ .'/ShipmentItemType.php',
        'App\DHL\ShipmentItemTypeType' => __DIR__ .'/ShipmentItemTypeType.php',
        'App\DHL\ShipmentService' => __DIR__ .'/ShipmentService.php',
        'App\DHL\Serviceconfiguration' => __DIR__ .'/Serviceconfiguration.php',
        'App\DHL\ServiceconfigurationDetails' => __DIR__ .'/ServiceconfigurationDetails.php',
        'App\DHL\ServiceconfigurationDetailsOptional' => __DIR__ .'/ServiceconfigurationDetailsOptional.php',
        'App\DHL\ServiceconfigurationDetailsResponse' => __DIR__ .'/ServiceconfigurationDetailsResponse.php',
        'App\DHL\ServiceconfigurationType' => __DIR__ .'/ServiceconfigurationType.php',
        'App\DHL\ServiceconfigurationEndorsement' => __DIR__ .'/ServiceconfigurationEndorsement.php',
        'App\DHL\ServiceconfigurationISR' => __DIR__ .'/ServiceconfigurationISR.php',
        'App\DHL\ServiceconfigurationDH' => __DIR__ .'/ServiceconfigurationDH.php',
        'App\DHL\ServiceconfigurationVisualAgeCheck' => __DIR__ .'/ServiceconfigurationVisualAgeCheck.php',
        'App\DHL\ServiceconfigurationDeliveryTimeframe' => __DIR__ .'/ServiceconfigurationDeliveryTimeframe.php',
        'App\DHL\ServiceconfigurationDateOfDelivery' => __DIR__ .'/ServiceconfigurationDateOfDelivery.php',
        'App\DHL\ServiceconfigurationAdditionalInsurance' => __DIR__ .'/ServiceconfigurationAdditionalInsurance.php',
        'App\DHL\ServiceconfigurationCashOnDelivery' => __DIR__ .'/ServiceconfigurationCashOnDelivery.php',
        'App\DHL\ServiceconfigurationShipmentHandling' => __DIR__ .'/ServiceconfigurationShipmentHandling.php',
        'App\DHL\ServiceconfigurationUnfree' => __DIR__ .'/ServiceconfigurationUnfree.php',
        'App\DHL\ServiceconfigurationIC' => __DIR__ .'/ServiceconfigurationIC.php',
        'App\DHL\ShipmentNotificationType' => __DIR__ .'/ShipmentNotificationType.php',
        'App\DHL\ExportDocumentType' => __DIR__ .'/ExportDocumentType.php',
        'App\DHL\ExportDocPosition' => __DIR__ .'/ExportDocPosition.php',
        'App\DHL\FurtherAddressesType' => __DIR__ .'/FurtherAddressesType.php',
        'App\DHL\DeliveryAdress' => __DIR__ .'/DeliveryAdress.php',
        'App\DHL\LabelData' => __DIR__ .'/LabelData.php',
        'App\DHL\ExportDocData' => __DIR__ .'/ExportDocData.php',
        'App\DHL\ManifestState' => __DIR__ .'/ManifestState.php',
        'App\DHL\DeletionState' => __DIR__ .'/DeletionState.php',
        'App\DHL\BookPickupRequest' => __DIR__ .'/BookPickupRequest.php',
        'App\DHL\BookPickupResponse' => __DIR__ .'/BookPickupResponse.php',
        'App\DHL\PickupDetailsType' => __DIR__ .'/PickupDetailsType.php',
        'App\DHL\PickupOrdererType' => __DIR__ .'/PickupOrdererType.php',
        'App\DHL\PickupBookingInformationType' => __DIR__ .'/PickupBookingInformationType.php',
        'App\DHL\CancelPickupRequest' => __DIR__ .'/CancelPickupRequest.php',
        'App\DHL\CancelPickupResponse' => __DIR__ .'/CancelPickupResponse.php',
        'App\DHL\IdentityData' => __DIR__ .'/IdentityData.php',
        'App\DHL\DrivingLicense' => __DIR__ .'/DrivingLicense.php',
        'App\DHL\IdentityCard' => __DIR__ .'/IdentityCard.php',
        'App\DHL\BankCard' => __DIR__ .'/BankCard.php',
        'App\DHL\PackstationType' => __DIR__ .'/PackstationType.php',
        'App\DHL\ReadShipmentOrderResponse' => __DIR__ .'/ReadShipmentOrderResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_e0abf0ee92872913d76e44772719e2ec');

// Do nothing. The rest is just leftovers from the code generation.
{
}
